inherit_from: .rubocop_m1.yml
Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'

Lint/HandleExceptions:
  Enabled: true
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'db/**/*'
