inherit_from: .rubocop_m1.yml
Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'app/views/**/*'

Lint/HandleExceptions:
  Enabled: true
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'db/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: rails
